name: alura
description: "Flutter project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.9
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3

dev_dependencies:

flutter_test:
  sdk: flutter

flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/nophoto.jpg
    - assets/splashscreen.png

  uses-material-design: true

flutter_native_splash:
  color: "#2196F3"
  image: assets/splashscreen.png
  android_12:
    image: assets/splashscreen.png
    color: "#2196F3"